name: collegecompanion
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  google_maps_flutter: ^2.1.8
  geolocator: ^13.0.2
  table_calendar: ^3.0.0 

  photo_view: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/images/campusmart.jpg
    - assets/images/menu1.jpg
    - assets/images/menu2.jpg
    - assets/images/menu3.jpg
    - assets/images/menu4.jpg
    - assets/images/salon.jpg
    - assets/images/stationary.jpg
    - assets/images/bmenu.jpg
